RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no # enable later
DYNAMIC_MACRO_ENABLE = yes
#KEY_LOCK_ENABLE = yes
#LEADER_ENABLE = yes # Leader key
#CAPS_WORD_ENABLE = yes
#KEY_OVERRIDE_ENABLE = yes # FOR USING JA KEYBOARD WITH US SYMBOLS
